import { Typography, Divider, Tag } from 'antd'
import { RobotOutlined, LinkOutlined } from '@ant-design/icons'

const { Paragraph, Text } = Typography

interface Props {
  summary: string
  period: string
}

/**
 * Split a grounded executive summary into its body and the trailing
 * "Sources:" citation line.
 *
 * The narrator is instructed to end with a blank line, then a line starting
 * with "Sources: ", with individual citations separated by " · ". We tolerate
 * a single newline (or a leading blank line) before the marker so minor
 * whitespace drift from the model still parses. Reports without a Sources line
 * (older reports) return the whole string as the body with no citations.
 */
export function parseSummary(raw: string): { body: string; citations: string[] } {
  const match = raw.match(/\n+Sources:[ \t]*/)
  if (!match || match.index === undefined) return { body: raw, citations: [] }
  const body = raw.slice(0, match.index).trimEnd()
  const rest = raw.slice(match.index + match[0].length)
  const citations = rest
    .split('·')
    .map((c) => c.trim())
    .filter(Boolean)
  return { body, citations }
}

export default function ExecutiveSummary({ summary, period }: Props) {
  const { body, citations } = parseSummary(summary)

  return (
    <div style={{ minHeight: 240 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
        <RobotOutlined style={{ color: '#6366f1' }} />
        <Text type="secondary" style={{ fontSize: 12 }}>
          Generated by Qwen2.5-72B · Nebius Serverless AI Endpoint
        </Text>
        <Tag color="purple">{period}</Tag>
        {citations.length > 0 && (
          <Tag color="blue" icon={<LinkOutlined />}>
            {citations.length} source{citations.length !== 1 ? 's' : ''}
          </Tag>
        )}
      </div>
      <Divider style={{ margin: '0 0 16px' }} />
      <Paragraph style={{ lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>
        {body}
      </Paragraph>
      {citations.length > 0 && (
        <>
          <Divider style={{ margin: '16px 0 10px' }} />
          <Text type="secondary" style={{ fontSize: 11 }}>Grounded sources: </Text>
          {citations.map((c, i) => (
            <Tag key={i} color="geekblue" style={{ fontSize: 11, marginTop: 4 }}>{c}</Tag>
          ))}
        </>
      )}
    </div>
  )
}
