import { Typography, Divider, Tag } from 'antd'
import { RobotOutlined } from '@ant-design/icons'

const { Paragraph, Text } = Typography

interface Props {
  summary: string
  period: string
}

export default function ExecutiveSummary({ summary, period }: Props) {
  return (
    <div style={{ minHeight: 240 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
        <RobotOutlined style={{ color: '#6366f1' }} />
        <Text type="secondary" style={{ fontSize: 12 }}>
          Generated by Qwen2.5-72B · Nebius Serverless AI Endpoint
        </Text>
        <Tag color="purple">{period}</Tag>
      </div>
      <Divider style={{ margin: '0 0 16px' }} />
      <Paragraph style={{ lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>
        {summary}
      </Paragraph>
    </div>
  )
}
