#!/usr/bin/env python3
"""Technical gate for the canonical Archon challenge video.

The canonical video is the fact-reviewed v4 presentation generated by
``scripts/build_video_v4.py``. Unlike the retired Playwright tour, each slide is
already paired with its narration, so the default gate validates the delivered
MP4 directly: challenge duration, 1080p video, an audio stream, and matching
audio/video lengths. Optional standalone narration or caption files can still be
checked when supplied explicitly.

Usage:
  python scripts/verify_video_sync.py
  python scripts/verify_video_sync.py --mp4 demo/archon-nebius-demo.mp4
  python scripts/verify_video_sync.py --voiceover narration.mp3
  python scripts/verify_video_sync.py --captions path/to/captions.txt

Exit code 0 = PASS, 1 = FAIL. Requires ffprobe on PATH.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from fractions import Fraction
from pathlib import Path


MP4_MIN = 180.0
MP4_MAX = 600.0
AV_GAP_MAX = 0.5
VOICEOVER_GAP_MAX = 3.0


def probe(path: Path) -> dict:
    result = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration:stream=codec_name,codec_type,width,height,r_frame_rate,duration",
            "-of",
            "json",
            str(path),
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def duration(path: Path) -> float:
    return float(probe(path)["format"]["duration"])


def caption_max_end(path: Path) -> float:
    end = 0.0
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.strip().split("|")
        if len(parts) < 2:
            continue
        try:
            end = max(end, float(parts[1]))
        except ValueError:
            pass
    return end


def stream_duration(stream: dict, fallback: float) -> float:
    value = stream.get("duration")
    return float(value) if value not in (None, "N/A") else fallback


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mp4", default="demo/archon-nebius-demo.mp4")
    parser.add_argument("--voiceover", default=None)
    parser.add_argument("--captions", default=None)
    args = parser.parse_args()

    if not shutil.which("ffprobe"):
        print("FAIL: ffprobe not found on PATH", file=sys.stderr)
        return 1

    mp4 = Path(args.mp4)
    if not mp4.exists():
        print(f"FAIL: mp4 not found: {mp4}", file=sys.stderr)
        return 1

    try:
        metadata = probe(mp4)
    except (subprocess.CalledProcessError, json.JSONDecodeError, KeyError, ValueError) as exc:
        print(f"FAIL: could not probe {mp4}: {exc}", file=sys.stderr)
        return 1

    mp4_duration = float(metadata["format"]["duration"])
    video = next((s for s in metadata.get("streams", []) if s.get("codec_type") == "video"), None)
    audio = next((s for s in metadata.get("streams", []) if s.get("codec_type") == "audio"), None)

    checks: list[tuple[bool, str]] = []
    checks.append(
        (MP4_MIN <= mp4_duration <= MP4_MAX,
         f"duration {mp4_duration:.1f}s in challenge range [{MP4_MIN:.0f}, {MP4_MAX:.0f}]")
    )
    checks.append((video is not None, "video stream present"))
    checks.append((audio is not None, "audio stream present"))

    if video:
        width = int(video.get("width", 0))
        height = int(video.get("height", 0))
        checks.append((width == 1920 and height == 1080, f"video is 1920x1080 (found {width}x{height})"))
        try:
            fps = float(Fraction(video.get("r_frame_rate", "0/1")))
        except (ValueError, ZeroDivisionError):
            fps = 0.0
        checks.append((fps >= 24.0, f"frame rate {fps:.2f} fps >= 24"))

    if video and audio:
        video_duration = stream_duration(video, mp4_duration)
        audio_duration = stream_duration(audio, mp4_duration)
        gap = abs(video_duration - audio_duration)
        checks.append((gap <= AV_GAP_MAX, f"audio/video duration gap {gap:.3f}s <= {AV_GAP_MAX:.1f}s"))

    if args.voiceover:
        voiceover = Path(args.voiceover)
        if not voiceover.exists():
            print(f"FAIL: voiceover not found: {voiceover}", file=sys.stderr)
            return 1
        voiceover_duration = duration(voiceover)
        gap = mp4_duration - voiceover_duration
        checks.append((voiceover_duration <= mp4_duration + AV_GAP_MAX,
                       f"voiceover {voiceover_duration:.1f}s is not clipped by {mp4_duration:.1f}s video"))
        checks.append((gap <= VOICEOVER_GAP_MAX,
                       f"video minus voiceover {gap:.1f}s <= {VOICEOVER_GAP_MAX:.0f}s"))

    if args.captions:
        captions = Path(args.captions)
        if not captions.exists():
            print(f"FAIL: captions not found: {captions}", file=sys.stderr)
            return 1
        caption_end = caption_max_end(captions)
        checks.append((caption_end <= mp4_duration + AV_GAP_MAX,
                       f"captions end {caption_end:.1f}s within {mp4_duration:.1f}s video"))

    ok = True
    for passed, message in checks:
        print(f"[{'PASS' if passed else 'FAIL'}] {message}")
        ok = ok and passed

    print("VIDEO GATE:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
